name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: make build
    - name: run executable
      run: ./main
    - name: create report
      run: make report

  