name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependency
      run: sudo apt-get install lcov
    - name: build
      run: make build
    - name: run executable
      run: ./main
    - name: create report
      run: make report
    - name: update lcov report
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b coverage
        git add --all
        git commit -m "Update lcov report"
        git push -f origin coverage
